### ISSUE TITLE
Test configuration

### ISSUE THREAD

**Issue by naomijub** [protojure/protoc-plugin#63]
Can you please include a test configuration for the resulting template? I have been trying to create a test but doesn't matter what I send it always return an empty body

**Comment by Rkiouak** [comment]
Hi @naomijub, I believe something like https://github.com/protojure/lein-template/pull/23 is what you were looking for?

**Comment by naomijub** [comment]
Exactly what I was missing. I was trying to call the service like a regular Pedestal REST API and not with the generated grpc client, `@(greeter-client/Hello @(grpc.http2/connect {:uri (str "http://localhost:" (:port @test-env))}) {:name "John Doe"})))`. Thanks
